<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ include file="/components/header.jsp" %>
<%@ include file="/components/global_ui.jsp" %>

<main style="padding-top: 100px; padding-bottom: 80px; background: #080808; min-height: 100vh;">
    <div class="container mx-auto max-w-xl px-4">

        <!-- Step Progress Bar -->
        <div class="mb-8">
            <jsp:include page="/components/booking-stepper.jsp">
                <jsp:param name="step" value="4"/>
                <jsp:param name="type" value="trip"/>
            </jsp:include>
        </div>

        <h1 class="text-3xl font-bold mb-6 editorial text-center">Complete Your Payment</h1>

        <div class="surface-panel rounded-2xl p-6 md:p-8 shadow-xl text-center">
            
            <div class="mb-6">
                <div class="text-sm text-gray-500 mb-1">Total Amount Payable</div>
                <div class="text-4xl font-bold text-primary">₹<fmt:formatNumber value="${totalPrice}" type="number" maxFractionDigits="0"/></div>
            </div>

            <div class="bg-blue-50 dark:bg-blue-900/20 text-blue-800 dark:text-blue-200 p-4 rounded-xl text-sm mb-8 text-left flex gap-3">
                <i class="fas fa-shield-alt text-xl mt-1"></i>
                <div>
                    <p class="font-bold mb-1">Secure Checkout</p>
                    <p>All transactions are secure and encrypted. We do not store your payment information on our servers.</p>
                </div>
            </div>

            <!-- Razorpay Button Container -->
            <button id="rzp-button1" class="btn-primary w-full py-4 rounded-xl text-lg font-bold shadow-lg transform transition-transform hover:-translate-y-1 flex items-center justify-center gap-3">
                <img src="https://razorpay.com/assets/razorpay-glyph.svg" alt="Razorpay" class="w-6 h-6 filter brightness-0 invert">
                Pay Securely with Razorpay
            </button>
            <p class="text-xs text-gray-500 mt-4">By proceeding, you agree to our Terms of Service and Cancellation Policy.</p>

        </div>

        <!-- Hidden form submitted after Razorpay success -->
        <form id="successForm" action="${pageContext.request.contextPath}/api/trip/booking-success" method="POST" style="display:none;">
            <input type="hidden" name="tripId" value="${tripId}">
            <input type="hidden" name="tripTitle" value="${tripTitle}">
            <input type="hidden" name="tripDest" value="${tripDest}">
            <input type="hidden" name="departureDate" value="${departureDate}">
            <input type="hidden" name="firstName" value="${firstName}">
            <input type="hidden" name="lastName" value="${lastName}">
            <input type="hidden" name="guestEmail" value="${guestEmail}">
            <input type="hidden" name="guestPhone" value="${guestPhone}">
            <input type="hidden" name="guests" value="${guests}">
            <input type="hidden" name="totalPrice" value="${totalPrice}">
            <input type="hidden" name="paymentId" id="paymentId" value="">
        </form>

    </div>
</main>

<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
    document.getElementById('rzp-button1').onclick = function(e) {
        e.preventDefault();
        
        // Secure Razorpay integration
        var options = {
            "key": "<%= com.voyastra.util.RazorpayConfig.getKeyId() %>", 
            "amount": parseInt("${totalPrice}") * 100, // Amount is in currency subunits
            "currency": "INR",
            "name": "Voyastra Premium Trips",
            "description": "Payment for ${tripTitle}",
            "image": "https://voyastra.com/logo.png",
            "order_id": "${razorpayOrderId}", // Securely generated by TripPaymentServlet
            "handler": function (response) {
                // Payment Success
                document.getElementById('paymentId').value = response.razorpay_payment_id;
                document.getElementById('successForm').submit();
            },
            "prefill": {
                "name": "${firstName} ${lastName}",
                "email": "${guestEmail}",
                "contact": "${guestPhone}"
            },
            "theme": {
                "color": "#8B5CF6"
            }
        };

        var rzp1 = new Razorpay(options);
        
        rzp1.on('payment.failed', function (response){
            alert("Payment Failed: " + response.error.description);
        });

        rzp1.open();
    }
</script>

<%@ include file="/components/footer.jsp" %>
