package com.voyastra.model.planner;

public enum PlannerStatus {
    REQUEST_RECEIVED,
    VALIDATING_INPUT,
    GENERATING_ITINERARY,
    FETCHING_IMAGES,
    FETCHING_VIDEOS,
    CALCULATING_BUDGET,
    RENDERING_PAGE,
    COMPLETED,
    FAILED,
    DESTINATION_SUCCESS,
    CACHE_NOT_USED,
    BUILDING_ITINERARY
}
