/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.117
 * Generated at: 2026-04-22 20:49:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class error_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    java.lang.Throwable exception = org.apache.jasper.runtime.JspRuntimeLibrary.getThrowable(request);
    if (exception != null) {
      response.setStatus(javax.servlet.http.HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
    }
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>System Error | Voyastra</title>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;800&family=Inter:wght@400;500&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <style>\n");
      out.write("        :root {\n");
      out.write("            --primary: #4f46e5;\n");
      out.write("            --bg: #0d0d11;\n");
      out.write("            --text: #f9fafb;\n");
      out.write("            --text-muted: rgba(249, 250, 251, 0.5);\n");
      out.write("        }\n");
      out.write("        body {\n");
      out.write("            background-color: var(--bg);\n");
      out.write("            color: var(--text);\n");
      out.write("            font-family: 'Poppins', 'Inter', 'Roboto', 'Arial', sans-serif;\n");
      out.write("            margin: 0;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            min-height: 100vh;\n");
      out.write("            overflow: hidden;\n");
      out.write("            text-align: center;\n");
      out.write("        }\n");
      out.write("        .container {\n");
      out.write("            max-width: 500px;\n");
      out.write("            padding: 40px;\n");
      out.write("            position: relative;\n");
      out.write("            z-index: 10;\n");
      out.write("        }\n");
      out.write("        .error-code {\n");
      out.write("            font-family: 'Poppins', 'Inter', 'Roboto', 'Arial', sans-serif;\n");
      out.write("            font-size: 10rem;\n");
      out.write("            font-weight: 800;\n");
      out.write("            margin: 0;\n");
      out.write("            background: linear-gradient(135deg, #4f46e5, #06b6d4);\n");
      out.write("            -webkit-background-clip: text;\n");
      out.write("            background-clip: text;\n");
      out.write("            -webkit-text-fill-color: transparent;\n");
      out.write("            opacity: 0.8;\n");
      out.write("            line-height: 1;\n");
      out.write("        }\n");
      out.write("        h1 {\n");
      out.write("            font-family: 'Poppins', 'Inter', 'Roboto', 'Arial', sans-serif;\n");
      out.write("            font-size: 1.8rem;\n");
      out.write("            margin: 20px 0 10px;\n");
      out.write("        }\n");
      out.write("        p {\n");
      out.write("            color: var(--text-muted);\n");
      out.write("            line-height: 1.6;\n");
      out.write("            margin-bottom: 30px;\n");
      out.write("        }\n");
      out.write("        .error-id {\n");
      out.write("            background: rgba(255,255,255,0.05);\n");
      out.write("            border: 1px solid rgba(255,255,255,0.1);\n");
      out.write("            padding: 10px 15px;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            font-family: monospace;\n");
      out.write("            display: inline-block;\n");
      out.write("            margin-bottom: 30px;\n");
      out.write("            font-size: 0.9rem;\n");
      out.write("        }\n");
      out.write("        .btn {\n");
      out.write("            display: inline-block;\n");
      out.write("            background: white;\n");
      out.write("            color: #0d0d11;\n");
      out.write("            padding: 14px 28px;\n");
      out.write("            border-radius: 10px;\n");
      out.write("            text-decoration: none;\n");
      out.write("            font-weight: 600;\n");
      out.write("            transition: 0.3s;\n");
      out.write("            box-shadow: 0 10px 20px rgba(0,0,0,0.3);\n");
      out.write("        }\n");
      out.write("        .btn:hover {\n");
      out.write("            transform: translateY(-2px);\n");
      out.write("            box-shadow: 0 15px 30px rgba(0,0,0,0.4);\n");
      out.write("        }\n");
      out.write("        /* Background decor */\n");
      out.write("        .orb {\n");
      out.write("            position: absolute;\n");
      out.write("            border-radius: 50%;\n");
      out.write("            filter: blur(100px);\n");
      out.write("            z-index: 1;\n");
      out.write("        }\n");
      out.write("        .orb-1 { width: 400px; height: 400px; background: rgba(79, 70, 229, 0.15); top: -100px; left: -100px; }\n");
      out.write("        .orb-2 { width: 300px; height: 300px; background: rgba(6, 182, 212, 0.1); bottom: -50px; right: -50px; }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"orb orb-1\"></div>\n");
      out.write("    <div class=\"orb orb-2\"></div>\n");
      out.write("\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"error-code\">\n");
      out.write("            ");
 
                Object code = request.getAttribute("javax.servlet.error.status_code");
                out.print(code != null ? code : "!!!");
            
      out.write("\n");
      out.write("        </div>\n");
      out.write("        <h1>Oops! Systems offline.</h1>\n");
      out.write("        <p>\n");
      out.write("            It seems we've encountered a slight distortion in the space-time continuum. \n");
      out.write("            Our engineers have been notified and are on it.\n");
      out.write("        </p>\n");
      out.write("        \n");
      out.write("        <div class=\"error-id\">\n");
      out.write("            Event ID: ");
      out.print( request.getAttribute("errorId") != null ? request.getAttribute("errorId") : "SYSTEM_FAILURE" );
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div>\n");
      out.write("            <a href=\"index.jsp\" class=\"btn\">Take Me Home</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
