/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.117
 * Generated at: 2026-04-08 11:58:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1775331836000L));
    _jspx_dependants.put("jar:file:/C:/Users/Dell/Desktop/antigravity/tomcat/apache-tomcat-9.0.117/webapps/voyastra/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Login — Voyastra</title>\n");
      out.write("    <link rel=\"icon\" type=\"image/svg+xml\" href=\"images/favicon.svg\">\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&family=Inter:wght@400;500;600;700&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/theme.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/components.css\">\n");
      out.write("    <script src=\"js/auth-guard.js\"></script>\n");
      out.write("    <script src=\"js/toast.js\"></script>\n");
      out.write("    <!-- Google Identity Services -->\n");
      out.write("    <script src=\"https://accounts.google.com/gsi/client\" async defer></script>\n");
      out.write("    <!-- Expose Java session to JS (prevents redirect loop) -->\n");
      out.write("    <script>\n");
      out.write("        (function(){\n");
      out.write("            var t = localStorage.getItem('theme'); \n");
      out.write("            if (t) document.documentElement.setAttribute('data-theme', t);\n");
      out.write("        })();\n");
      out.write("        window.javaSession = {\n");
      out.write("            userId: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\",\n");
      out.write("            role:   \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.role}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\",\n");
      out.write("            name:   \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\",\n");
      out.write("            email:  \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\n");
      out.write("        };\n");
      out.write("        // If already logged in server-side, skip login page immediately\n");
      out.write("        if (window.javaSession.userId && window.javaSession.userId.length > 0) {\n");
      out.write("            if (window.javaSession.role === 'admin') {\n");
      out.write("                window.location.replace('admin-home.jsp');\n");
      out.write("            } else {\n");
      out.write("                window.location.replace('dashboard.jsp');\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("\n");
      out.write("    <style>\n");
      out.write("        /* ── Login Page Exclusive Styles ── */\n");
      out.write("        body { cursor: auto !important; display: flex; min-height: 100vh; }\n");
      out.write("\n");
      out.write("        .login-split {\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: 1fr 1fr;\n");
      out.write("            min-height: 100vh;\n");
      out.write("            width: 100%;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Left — brand panel */\n");
      out.write("        .login-brand-panel {\n");
      out.write("            position: relative;\n");
      out.write("            background: #0d0d11;\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            padding: 60px;\n");
      out.write("            overflow: hidden;\n");
      out.write("        }\n");
      out.write("        .login-brand-panel::before {\n");
      out.write("            content: '';\n");
      out.write("            position: absolute;\n");
      out.write("            inset: 0;\n");
      out.write("            background: radial-gradient(ellipse at 30% 50%, rgba(79,70,229,0.18) 0%, transparent 70%),\n");
      out.write("                        radial-gradient(ellipse at 80% 20%, rgba(6,182,212,0.12) 0%, transparent 60%);\n");
      out.write("            pointer-events: none;\n");
      out.write("        }\n");
      out.write("        .login-brand-svg {\n");
      out.write("            width: 200px;\n");
      out.write("            height: 100px;\n");
      out.write("            margin-bottom: 32px;\n");
      out.write("            opacity: 0;\n");
      out.write("            animation: loginBrandIn 1s 0.3s ease forwards;\n");
      out.write("        }\n");
      out.write("        .login-brand-title {\n");
      out.write("            font-family: 'Poppins', sans-serif;\n");
      out.write("            font-size: 2.8rem;\n");
      out.write("            font-weight: 800;\n");
      out.write("            letter-spacing: -0.02em;\n");
      out.write("            color: #ffffff;\n");
      out.write("            margin-bottom: 12px;\n");
      out.write("            opacity: 0;\n");
      out.write("            animation: loginBrandIn 1s 0.5s ease forwards;\n");
      out.write("        }\n");
      out.write("        .login-brand-sub {\n");
      out.write("            font-family: 'Poppins', sans-serif;\n");
      out.write("            font-size: 0.95rem;\n");
      out.write("            font-weight: 400;\n");
      out.write("            color: rgba(255,255,255,0.5);\n");
      out.write("            text-align: center;\n");
      out.write("            max-width: 280px;\n");
      out.write("            line-height: 1.7;\n");
      out.write("            opacity: 0;\n");
      out.write("            animation: loginBrandIn 1s 0.7s ease forwards;\n");
      out.write("        }\n");
      out.write("        .login-brand-dots {\n");
      out.write("            position: absolute;\n");
      out.write("            bottom: 40px;\n");
      out.write("            display: flex;\n");
      out.write("            gap: 8px;\n");
      out.write("            opacity: 0.3;\n");
      out.write("        }\n");
      out.write("        .login-brand-dots span {\n");
      out.write("            width: 6px; height: 6px;\n");
      out.write("            border-radius: 50%;\n");
      out.write("            background: #06b6d4;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Right — form panel */\n");
      out.write("        .login-form-panel {\n");
      out.write("            background: #ffffff;\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            padding: 60px 80px;\n");
      out.write("        }\n");
      out.write("        [data-theme=\"dark\"] .login-form-panel { background: #0f0f14; }\n");
      out.write("\n");
      out.write("        .login-form-wrap {\n");
      out.write("            width: 100%;\n");
      out.write("            max-width: 380px;\n");
      out.write("            opacity: 0;\n");
      out.write("            animation: loginFormIn 0.9s 0.4s cubic-bezier(0.25,1,0.5,1) forwards;\n");
      out.write("        }\n");
      out.write("        .login-eyebrow {\n");
      out.write("            font-family: 'Poppins', sans-serif;\n");
      out.write("            font-size: 0.72rem;\n");
      out.write("            font-weight: 700;\n");
      out.write("            letter-spacing: 0.18em;\n");
      out.write("            text-transform: uppercase;\n");
      out.write("            color: #4f46e5;\n");
      out.write("            margin-bottom: 10px;\n");
      out.write("        }\n");
      out.write("        .login-heading {\n");
      out.write("            font-family: 'Poppins', sans-serif;\n");
      out.write("            font-size: 2rem;\n");
      out.write("            font-weight: 800;\n");
      out.write("            letter-spacing: -0.03em;\n");
      out.write("            color: #0f0b08;\n");
      out.write("            margin-bottom: 6px;\n");
      out.write("        }\n");
      out.write("        [data-theme=\"dark\"] .login-heading { color: #ffffff; }\n");
      out.write("        .login-subhead {\n");
      out.write("            font-family: 'Inter', sans-serif;\n");
      out.write("            font-size: 0.88rem;\n");
      out.write("            color: rgba(15,11,8,0.5);\n");
      out.write("            margin-bottom: 36px;\n");
      out.write("        }\n");
      out.write("        [data-theme=\"dark\"] .login-subhead { color: rgba(255,255,255,0.4); }\n");
      out.write("\n");
      out.write("        /* Form fields */\n");
      out.write("        .login-field {\n");
      out.write("            position: relative;\n");
      out.write("            margin-bottom: 18px;\n");
      out.write("        }\n");
      out.write("        .login-field label {\n");
      out.write("            display: block;\n");
      out.write("            font-family: 'Poppins', sans-serif;\n");
      out.write("            font-size: 0.78rem;\n");
      out.write("            font-weight: 600;\n");
      out.write("            color: #0f0b08;\n");
      out.write("            margin-bottom: 7px;\n");
      out.write("            letter-spacing: 0.03em;\n");
      out.write("        }\n");
      out.write("        [data-theme=\"dark\"] .login-field label { color: rgba(255,255,255,0.75); }\n");
      out.write("        .login-field input {\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 13px 16px;\n");
      out.write("            border: 1.5px solid rgba(15,11,8,0.15);\n");
      out.write("            border-radius: 10px;\n");
      out.write("            font-family: 'Inter', sans-serif;\n");
      out.write("            font-size: 0.92rem;\n");
      out.write("            color: #0f0b08;\n");
      out.write("            background: #fafafa;\n");
      out.write("            outline: none;\n");
      out.write("            transition: border-color 0.2s, box-shadow 0.2s;\n");
      out.write("            box-sizing: border-box;\n");
      out.write("            cursor: text !important;\n");
      out.write("        }\n");
      out.write("        [data-theme=\"dark\"] .login-field input {\n");
      out.write("            background: rgba(255,255,255,0.05);\n");
      out.write("            border-color: rgba(255,255,255,0.12);\n");
      out.write("            color: #ffffff;\n");
      out.write("        }\n");
      out.write("        .login-field input:focus {\n");
      out.write("            border-color: #4f46e5;\n");
      out.write("            box-shadow: 0 0 0 3px rgba(79,70,229,0.12);\n");
      out.write("        }\n");
      out.write("        .login-field input::placeholder { color: rgba(15,11,8,0.35); }\n");
      out.write("        [data-theme=\"dark\"] .login-field input::placeholder { color: rgba(255,255,255,0.25); }\n");
      out.write("\n");
      out.write("        /* Toggle password */\n");
      out.write("        .login-field .pw-toggle {\n");
      out.write("            position: absolute;\n");
      out.write("            right: 14px;\n");
      out.write("            top: 38px;\n");
      out.write("            background: none;\n");
      out.write("            border: none;\n");
      out.write("            cursor: pointer !important;\n");
      out.write("            color: rgba(15,11,8,0.35);\n");
      out.write("            padding: 0;\n");
      out.write("            line-height: 1;\n");
      out.write("        }\n");
      out.write("        [data-theme=\"dark\"] .pw-toggle { color: rgba(255,255,255,0.3); }\n");
      out.write("        .login-field .pw-toggle:hover { color: #4f46e5; }\n");
      out.write("\n");
      out.write("        /* Error message */\n");
      out.write("        #loginError {\n");
      out.write("            display: none;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 8px;\n");
      out.write("            background: rgba(239,68,68,0.08);\n");
      out.write("            border: 1px solid rgba(239,68,68,0.25);\n");
      out.write("            border-radius: 8px;\n");
      out.write("            padding: 10px 14px;\n");
      out.write("            font-family: 'Inter', sans-serif;\n");
      out.write("            font-size: 0.82rem;\n");
      out.write("            color: #ef4444;\n");
      out.write("            margin-bottom: 18px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Hint */\n");
      out.write("        .login-hint {\n");
      out.write("            font-family: 'Inter', sans-serif;\n");
      out.write("            font-size: 0.76rem;\n");
      out.write("            color: rgba(15,11,8,0.35);\n");
      out.write("            background: rgba(79,70,229,0.06);\n");
      out.write("            border-radius: 8px;\n");
      out.write("            padding: 10px 14px;\n");
      out.write("            margin-bottom: 22px;\n");
      out.write("            line-height: 1.6;\n");
      out.write("        }\n");
      out.write("        [data-theme=\"dark\"] .login-hint {\n");
      out.write("            color: rgba(255,255,255,0.35);\n");
      out.write("            background: rgba(79,70,229,0.1);\n");
      out.write("        }\n");
      out.write("        .login-hint code {\n");
      out.write("            font-weight: 700;\n");
      out.write("            color: #4f46e5;\n");
      out.write("            background: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Submit button */\n");
      out.write("        .login-btn {\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 14px;\n");
      out.write("            background: #0f0b08;\n");
      out.write("            color: #ffffff;\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 10px;\n");
      out.write("            font-family: 'Poppins', sans-serif;\n");
      out.write("            font-size: 0.9rem;\n");
      out.write("            font-weight: 700;\n");
      out.write("            letter-spacing: 0.06em;\n");
      out.write("            text-transform: uppercase;\n");
      out.write("            cursor: pointer !important;\n");
      out.write("            transition: background 0.2s, transform 0.15s, box-shadow 0.2s;\n");
      out.write("        }\n");
      out.write("        [data-theme=\"dark\"] .login-btn { background: #ffffff; color: #0f0b08; }\n");
      out.write("        .login-btn:hover { background: #1a1510; transform: translateY(-1px); box-shadow: 0 6px 20px rgba(0,0,0,0.2); }\n");
      out.write("        [data-theme=\"dark\"] .login-btn:hover { background: #f0f0f0; }\n");
      out.write("        .login-btn:active { transform: translateY(0); }\n");
      out.write("        .login-btn.loading { opacity: 0.65; pointer-events: none; }\n");
      out.write("\n");
      out.write("        /* Back link */\n");
      out.write("        .login-back {\n");
      out.write("            display: inline-flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 6px;\n");
      out.write("            font-family: 'Inter', sans-serif;\n");
      out.write("            font-size: 0.82rem;\n");
      out.write("            color: rgba(15,11,8,0.45);\n");
      out.write("            text-decoration: none;\n");
      out.write("            margin-top: 24px;\n");
      out.write("            cursor: pointer !important;\n");
      out.write("            transition: color 0.2s;\n");
      out.write("        }\n");
      out.write("        [data-theme=\"dark\"] .login-back { color: rgba(255,255,255,0.3); }\n");
      out.write("        .login-back:hover { color: #4f46e5; }\n");
      out.write("\n");
      out.write("        /* Animations */\n");
      out.write("        @keyframes loginBrandIn {\n");
      out.write("            from { opacity: 0; transform: translateY(20px); }\n");
      out.write("            to   { opacity: 1; transform: translateY(0); }\n");
      out.write("        }\n");
      out.write("        @keyframes loginFormIn {\n");
      out.write("            from { opacity: 0; transform: translateX(24px); }\n");
      out.write("            to   { opacity: 1; transform: translateX(0); }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Floating orbs on brand panel */\n");
      out.write("        .orb {\n");
      out.write("            position: absolute;\n");
      out.write("            border-radius: 50%;\n");
      out.write("            filter: blur(60px);\n");
      out.write("            pointer-events: none;\n");
      out.write("        }\n");
      out.write("        .orb-1 { width: 300px; height: 300px; background: rgba(79,70,229,0.15); top: -80px; left: -60px; }\n");
      out.write("        .orb-2 { width: 200px; height: 200px; background: rgba(6,182,212,0.12); bottom: 60px; right: -40px; }\n");
      out.write("\n");
      out.write("        /* Mobile */\n");
      out.write("        @media (max-width: 768px) {\n");
      out.write("            .login-split { grid-template-columns: 1fr; }\n");
      out.write("            .login-brand-panel { display: none; }\n");
      out.write("            .login-form-panel { padding: 40px 28px; }\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"login-split\">\n");
      out.write("    <!-- ── Left: Brand Panel ── -->\n");
      out.write("    <div class=\"login-brand-panel\">\n");
      out.write("        <div class=\"orb orb-1\"></div>\n");
      out.write("        <div class=\"orb orb-2\"></div>\n");
      out.write("\n");
      out.write("        <!-- Animated infinity SVG (same as preloader) -->\n");
      out.write("        <svg class=\"login-brand-svg\" viewBox=\"0 0 300 150\">\n");
      out.write("            <defs>\n");
      out.write("                <linearGradient id=\"loginGrad\" x1=\"0%\" y1=\"0%\" x2=\"100%\" y2=\"100%\">\n");
      out.write("                    <stop offset=\"0%\" stop-color=\"#4f46e5\" />\n");
      out.write("                    <stop offset=\"100%\" stop-color=\"#06b6d4\" />\n");
      out.write("                </linearGradient>\n");
      out.write("            </defs>\n");
      out.write("            <path fill=\"none\" stroke=\"url(#loginGrad)\" stroke-width=\"2.5\"\n");
      out.write("                  stroke-dasharray=\"800\" stroke-dashoffset=\"800\"\n");
      out.write("                  style=\"animation: loginPathDraw 3s cubic-bezier(0.4,0,0.2,1) 0.8s infinite;\"\n");
      out.write("                  d=\"M 150,75 C 200,15 300,15 300,75 C 300,135 200,135 150,75 C 100,15 0,15 0,75 C 0,135 100,135 150,75 Z\" />\n");
      out.write("        </svg>\n");
      out.write("        <style>\n");
      out.write("            @keyframes loginPathDraw {\n");
      out.write("                0%   { stroke-dashoffset: 800; }\n");
      out.write("                100% { stroke-dashoffset: 0; }\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("\n");
      out.write("        <div class=\"login-brand-title\">Voyastra</div>\n");
      out.write("        <div class=\"login-brand-sub\">Plan smarter. Travel better. Discover India like never before.</div>\n");
      out.write("        <div class=\"login-brand-dots\">\n");
      out.write("            <span></span><span style=\"opacity:0.6\"></span><span style=\"opacity:0.3\"></span>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- ── Right: Form Panel ── -->\n");
      out.write("    <div class=\"login-form-panel\">\n");
      out.write("        <div class=\"login-form-wrap\">\n");
      out.write("            <div class=\"login-eyebrow\">Welcome back</div>\n");
      out.write("            <h1 class=\"login-heading\">Sign in</h1>\n");
      out.write("            <p class=\"login-subhead\">Access your travel dashboard and itineraries.</p>\n");
      out.write("\n");
      out.write("            <!-- Demo credentials hint -->\n");
      out.write("            <div class=\"login-hint\">\n");
      out.write("                <strong>Demo credentials:</strong><br>\n");
      out.write("                Admin: <code>admin@voyastra.com</code> &nbsp;|&nbsp; Password: <code>1234</code><br>\n");
      out.write("                User: <code>arjun@example.com</code> &nbsp;|&nbsp; Password: <code>password123</code>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- Server-side error -->\n");
      out.write("            ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("            <!-- ── Google Login Button ── -->\n");
      out.write("            <div id=\"googleBtnWrap\" style=\"margin-bottom:20px;\">\n");
      out.write("                <div id=\"g_id_onload\"\n");
      out.write("                     data-client_id=\"321070392622-u0am1rhjl18u8b3lclfppkqtdqp88i3g.apps.googleusercontent.com\"\n");
      out.write("                     data-callback=\"handleGoogleCredential\"\n");
      out.write("                     data-auto_select=\"false\"\n");
      out.write("                     data-cancel_on_tap_outside=\"true\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"g_id_signin\"\n");
      out.write("                     data-type=\"standard\"\n");
      out.write("                     data-shape=\"rectangular\"\n");
      out.write("                     data-theme=\"filled_black\"\n");
      out.write("                     data-text=\"continue_with\"\n");
      out.write("                     data-size=\"large\"\n");
      out.write("                     data-width=\"360\"\n");
      out.write("                     data-logo_alignment=\"left\">\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- Divider -->\n");
      out.write("            <div style=\"display:flex; align-items:center; gap:12px; margin-bottom:20px;\">\n");
      out.write("                <div style=\"flex:1; height:1px; background:var(--color-border);\"></div>\n");
      out.write("                <span style=\"font-size:0.75rem; color:var(--text-muted); white-space:nowrap;\">or continue with email</span>\n");
      out.write("                <div style=\"flex:1; height:1px; background:var(--color-border);\"></div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- ── Email / Password Form ── -->\n");
      out.write("            <form action=\"login\" method=\"POST\" id=\"loginForm\" novalidate data-vx>\n");
      out.write("                <div class=\"login-field\">\n");
      out.write("                    <label for=\"loginEmail\">Email address</label>\n");
      out.write("                    <input type=\"email\" id=\"loginEmail\" name=\"email\" placeholder=\"you@example.com\" autocomplete=\"email\"\n");
      out.write("                           data-v-required data-v-email data-v-label=\"Email\">\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"login-field\">\n");
      out.write("                    <label for=\"loginPassword\">Password</label>\n");
      out.write("                    <input type=\"password\" id=\"loginPassword\" name=\"password\" placeholder=\"Enter your password\" autocomplete=\"current-password\"\n");
      out.write("                           data-v-required data-v-label=\"Password\">\n");
      out.write("                    <button type=\"button\" class=\"pw-toggle\" id=\"pwToggle\" aria-label=\"Show/hide password\">\n");
      out.write("                        <svg id=\"eyeIcon\" width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n");
      out.write("                            <path d=\"M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z\"/><circle cx=\"12\" cy=\"12\" r=\"3\"/>\n");
      out.write("                        </svg>\n");
      out.write("                    </button>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <button type=\"submit\" class=\"login-btn\" id=\"loginBtn\">Sign In</button>\n");
      out.write("            </form>\n");
      out.write("\n");
      out.write("            <div style=\"display:flex; flex-direction:column; align-items:center; gap:12px; margin-top:24px;\">\n");
      out.write("                <a href=\"register.jsp\" class=\"login-back\" style=\"margin-top:0;\">Don't have an account? Sign up</a>\n");
      out.write("                <a href=\"index.jsp\" class=\"login-back\" style=\"margin-top:0;\">\n");
      out.write("                    <svg width=\"14\" height=\"14\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><line x1=\"19\" y1=\"12\" x2=\"5\" y2=\"12\"/><polyline points=\"12 19 5 12 12 5\"/></svg>\n");
      out.write("                    Back to home\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    // ── Password visibility toggle\n");
      out.write("    document.getElementById('pwToggle').addEventListener('click', function () {\n");
      out.write("        var pw   = document.getElementById('loginPassword');\n");
      out.write("        var icon = document.getElementById('eyeIcon');\n");
      out.write("        if (pw.type === 'password') {\n");
      out.write("            pw.type = 'text';\n");
      out.write("            icon.innerHTML = '<path d=\"M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19m-6.72-1.07a3 3 0 1 1-4.24-4.24\"/><line x1=\"1\" y1=\"1\" x2=\"23\" y2=\"23\"/>';\n");
      out.write("        } else {\n");
      out.write("            pw.type = 'password';\n");
      out.write("            icon.innerHTML = '<path d=\"M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z\"/><circle cx=\"12\" cy=\"12\" r=\"3\"/>';\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    // ── Email/password form: show loading state on submit\n");
      out.write("    document.getElementById('loginForm').addEventListener('submit', function () {\n");
      out.write("        var btn = document.getElementById('loginBtn');\n");
      out.write("        btn.classList.add('loading');\n");
      out.write("        btn.textContent = 'Signing in…';\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    // ── Show toast if redirected for auth or after logout\n");
      out.write("    (function() {\n");
      out.write("        var params = new URLSearchParams(window.location.search);\n");
      out.write("        if (params.get('error') === 'auth_required') {\n");
      out.write("            setTimeout(function() {\n");
      out.write("                if (window.VoyastraToast) VoyastraToast.show('Please log in to continue.', 'warning');\n");
      out.write("            }, 200);\n");
      out.write("        }\n");
      out.write("        if (params.get('logout') === 'true') {\n");
      out.write("            localStorage.removeItem('voyastra_user');\n");
      out.write("            setTimeout(function() {\n");
      out.write("                if (window.VoyastraToast) VoyastraToast.show('You have been logged out.', 'info');\n");
      out.write("            }, 200);\n");
      out.write("        }\n");
      out.write("    })();\n");
      out.write("\n");
      out.write("    // ── Google OAuth callback — called by Google Identity Services\n");
      out.write("    function handleGoogleCredential(response) {\n");
      out.write("        var wrap = document.getElementById('googleBtnWrap');\n");
      out.write("        if (wrap) wrap.style.opacity = '0.6';\n");
      out.write("\n");
      out.write("        fetch('google-auth', {\n");
      out.write("            method: 'POST',\n");
      out.write("            headers: { 'Content-Type': 'application/json' },\n");
      out.write("            body: JSON.stringify({ credential: response.credential })\n");
      out.write("        })\n");
      out.write("        .then(function(res) { return res.json(); })\n");
      out.write("        .then(function(data) {\n");
      out.write("            if (data.success) {\n");
      out.write("                if (window.VoyastraToast) VoyastraToast.show('Welcome, ' + data.name + '!', 'success');\n");
      out.write("                setTimeout(function() { window.location.href = data.redirect; }, 600);\n");
      out.write("            } else {\n");
      out.write("                if (wrap) wrap.style.opacity = '1';\n");
      out.write("                if (window.VoyastraToast) VoyastraToast.show(data.error || 'Google login failed.', 'error');\n");
      out.write("            }\n");
      out.write("        })\n");
      out.write("        .catch(function() {\n");
      out.write("            if (wrap) wrap.style.opacity = '1';\n");
      out.write("            if (window.VoyastraToast) VoyastraToast.show('Network error. Please try again.', 'error');\n");
      out.write("        });\n");
      out.write("    }\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /login.jsp(363,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty errorMsg}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                <div id=\"loginError\" style=\"display:flex; align-items:center; gap:8px; padding:10px 14px; background:rgba(239,68,68,0.1); border:1px solid rgba(239,68,68,0.3); border-radius:8px; color:#ef4444; font-size:0.875rem; margin-bottom:16px;\">\n");
          out.write("                    <svg width=\"14\" height=\"14\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\"><circle cx=\"12\" cy=\"12\" r=\"10\"/><line x1=\"12\" y1=\"8\" x2=\"12\" y2=\"12\"/><line x1=\"12\" y1=\"16\" x2=\"12.01\" y2=\"16\"/></svg>\n");
          out.write("                    ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMsg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\n");
          out.write("                </div>\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    }
    return false;
  }
}
